### ISSUE TITLE
Display constructor takes uint8_t's for width and height

### ISSUE THREAD

**Issue by jeffc** [croutor/Adafruit_GFX_dummy_display#2]
Hey, thanks for your hard work on this project!

The constructor for this library takes uint8_t's for the width and height of the dummy display, which doesn't allow for any dimension larger than 255. Is there a technical reason for that, or is it an oversight? Everything else that takes xy coordinates in this library seems to take uint16_t's, as does the [upstream Adafruit_GFX Library](https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_GFX.h)

Thanks again!

**Comment by croutor** [comment]
Good point. I will try to rework that.

**Comment by croutor** [comment]
OK this has been reworked. Tell me how it works now. Thx!
